cargo-features = ["edition2021"]
[workspace]
members = [
    "merkle",
    "trie",
    "node",
    "crypto",
    "blockchain",
    "storage",
    "morph",
    "account",
    "common/traits",
    "common/uint",
    "common/primitive-types/impls/num-traits",
    "common/primitive-types/impls/serde",
    "common/primitive-types",
    "common/fixed-hash",
    "common/types",
    "common/tracing",
    "codec",
    "transaction",
    "txpool",
    "consensus",
    "miner"
]