cargo-features = ["edition2021"]
[workspace]
members = [
    #core
    "merkle",
    "trie",
    "uchain",
    "crypto",
    "blockchain",
    "storage",
    "state",
    "account",
    "codec",
    "transaction",
    "txpool",
    "consensus",
    "miner",
    "p2p",
    "smt",
    "proto",
    "rpc",
    #common
    "common/traits",
    "common/uint",
    "common/primitive-types/impls/num-traits",
    "common/primitive-types/impls/serde",
    "common/primitive-types",
    "common/prefix-hex",
    "common/fixed-hash",
    "common/types",
    "common/tracing",
    "common/rlp",
    "common/rlp-derive",
]