cargo-features = ["edition2021"]
[workspace]
members = [
    #core
    "merkle",
    "trie",
    "uchain",
    "crypto",
    "blockchain",
    "storage",
    "state",
    "account",
    "codec",
    "transaction",
    "txpool",
    "consensus",
    "miner",
    "p2p",
    "smt",
    "proto",
    "rpc",
    #common
    "common/traits",
    "common/uint",
    "common/primitive-types/impls/num-traits",
    "common/primitive-types/impls/serde",
    "common/primitive-types/impls/bincode",
    "common/primitive-types",
    "common/hex",
    "common/fixed-hash",
    "common/types",
    "common/tracing",
    "common/rlp",
    "common/rlp-derive",
    "common/tiny-bip39",
    "common/bech32",
]

[patch.crates-io]
prost = { git = 'https://github.com/mambisi/prost',  branch = "bytes-mod" }
