version: 0.0
os: linux
files:
  - source: ./odana
    destination: /usr/bin
hooks:
  AfterInstall:
    - location: Scripts/setup.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600
  ValidateService:
    - location: scripts/validate.sh
      timeout: 3600
      runas: codedeployuser
