version: 0.2

phases:
  install:
    command:
      - echo "Install Packages"
      - apt install -y clang libclang-dev llvm llvm-dev linux-kernel-headers libev-dev cmake libprotobuf-dev protobuf-compiler
      - echo "Rust is not installed. Installing with curl..."
      - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
      - source $HOME/.cargo/env
      - rustup target add wasm32-unknown-unknown
  build:
    commands:
      - echo Build started on `date`
      - cargo build --release
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/release/odana
    - appspec.yml
  discard-paths: yes