codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "78...100"
  status:
    project:
      default:
        target: auto
        informational: true
    patch:
      default:
        target: auto
