[package]
name = "prost-reflect-tests"
description = "Tests for prost-reflect."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
doctest = false

[[bench]]
name = "decode"
harness = false

[dependencies]
once_cell = "1.9.0"
prost = "0.11.0"
prost-reflect = { path = "../prost-reflect", features = [
    "serde",
    "derive",
    "text-format"
] }
prost-types = "0.11.0"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
serde_json = { version = "1.0.73", features = ["float_roundtrip"] }
serde = "1.0.132"
criterion = "0.4.0"
rayon = "1.5.3"

[build-dependencies]
prost-reflect-build = { path = "../prost-reflect-build" }
prost-build = "0.11.0"

[package.metadata.release]
release = false
