[package]
name = "odana-rt-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
odana-std = { path = "../../runtime/std", default-feature = false }

[features]
default = ["std"]
std = [
    "odana-std/std"
]