[package]
name = "wit-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen-gen-guest-rust = { git = "https://github.com/bytecodealliance/wit-bindgen.git" }
wit-bindgen-core = { git = "https://github.com/bytecodealliance/wit-bindgen.git" }
wit-parser = "0.3.1"
anyhow = { workspace = true }
wasmtime-wit-bindgen = { git = "https://github.com/bytecodealliance/wasmtime.git" }