[package]
name = "prost-reflect-conformance-tests"
description = "Protobuf test runner for prost-reflect."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false
build = "build.rs"

[[bin]]
name = "prost-reflect-conformance-tests"
test = false
doctest = false

[lib]
test = false
doctest = false

[dependencies]
prost = "0.11.0"
prost-types = "0.11.0"
prost-reflect = { path = "../prost-reflect", features = ["serde", "text-format"] }
env_logger = "0.10.0"
serde_json = { version = "1.0.74", features = ["float_roundtrip"] }
serde = "1.0.133"
once_cell = "1.9.0"

[dev-dependencies]

[build-dependencies]
tar = "0.4.38"
flate2 = "1.0.24"
ureq = "2.5.0"
anyhow = "1.0.58"
prost-build = "0.11.0"
tempfile = "3.3.0"

[package.metadata.release]
release = false
