[package]
name = "rune-framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen-guest-rust = { git = "https://github.com/padicresearch/wit-bindgen.git" }
rune-std = { path = "../std" }
prost = { workspace = true }
primitive-types = { workspace = true, default-features = false }
blake2b_simd = { version = "1.0.0", default-feature = false }
anyhow = { workspace = true, default-features = false }
prost-reflect = {version = "0.10.1", default-features = false, features = ["derive"]}
sha3 = "0.10.2"
digest = "0.10.3"
[build-dependencies]
wit-codegen = { workspace = true }