[package]
name = "account"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = "1.0.1"
rand = "0.7"
rand_chacha = "0.2"
tiny-keccak = { version = "2.0", features = ["keccak", "sha3"] }
rand_core = "0.5.0"
anyhow = "1.0.45"
storage = { path = "../storage" }
serde = { version = "1.0.130", features = ["derive"] }
hex = "0.4.3"
primitive-types = { path = "../common/primitive-types" }
crypto = { path = "../crypto" }
codec = { path = "../codec" }
types = { path = "../common/types" }