[package]
name = "rt-io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen-guest-rust = { git = "https://github.com/bytecodealliance/wit-bindgen.git" }
anyhow = { workspace = true }
prost = { workspace = true }
rt-std = { path = "../std", default-feature = false }
blake2b_simd = { version = "1.0.0", default-feature = false }
[build-dependencies]
wit-codegen = { workspace = true }
[features]
default = ["std"]
std = [
    "rt-std/std"
]