[package]
name = "odana-io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen-guest-rust = { git = "https://github.com/bytecodealliance/wit-bindgen.git" }
bincode = { workspace = true }
anyhow = { workspace = true }


odana-std = { path = "../std", default-feature = false }
[features]
default = ["std"]
std = [
    "odana-std/std"
]