[package]
name = "prost-extra-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = { workspace = true }
prost-build = { workspace = true }
prost-reflect = { workspace = true }
prost-extra-derive = {path = "../prost-extra-derive"}
[features]
derive = []