[package]
name = "node"
version = "0.1.0"
authors = ["mambisi <lilbizi96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
# Local Dependencies
crypto = {path = "../crypto"}
merkle = {path = "../merkle"}
blockchain = {path = "../blockchain"}
storage = {path = "../storage"}
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.45"