[package]
name = "node"
version = "0.1.0"
authors = ["mambisi <lilbizi96@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
# Local Dependencies
crypto = { path = "../crypto" }
merkle = { path = "../merkle" }
blockchain = { path = "../blockchain" }
p2p = { path = "../p2p" }
storage = { path = "../storage" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.45"
types = { path = "../common/types" }
txpool = { path = "../txpool" }
morph = { path = "../morph" }
consensus = { path = "../consensus" }
miner = { path = "../miner" }
account = { path = "../account" }
traits = { path = "../common/traits" }
tracing = { path = "../common/tracing" }
clap = { version = "3.0.13", features = ["derive"] }