[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-big-array = "0.3.2"
primitive-types = { path = "../primitive-types" }
serde = { version = "1.0.130", features = ["derive"] }
tiny-keccak = { version = "2.0", features = ["keccak", "sha3"] }
anyhow = "1"
derive-getters = "0.2.0"
hex = "0.4.3"
codec = { path = "../../codec" }
crypto = { path = "../../crypto" }
rmp-serde = "1.0.0"
serde_json = "1.0"
actix = "0.13"
[dev-dependencies]
rand = "0.7"
bincode = "1.0.130"