[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0.1"
serde-big-array = "0.4.1"
serde = { version = "1.0.130", features = ["derive", "rc"] }
tiny-keccak = { version = "2.0", features = ["keccak", "sha3"] }
anyhow = "1"
derive-getters = "0.2.0"
getset = "0.1.2"
num-traits = "0.2.15"
prost = "0.11.0"
prost-types = "0.11.0"
rmp-serde = "1.0.0"
serde_json = "1.0"
actix = "0.13"
bytes = { version = "1", features = ["serde"] }
clap = { version = "3.0.13", features = ["derive"] }
chrono = "0.4"
bincode = "2.0.0-rc.2"
# local deps
hex = { path = "../hex" }
primitive-types = { path = "../primitive-types" }
codec = { path = "../../codec" }
crypto = { path = "../../crypto" }
bech32 = { path = "../bech32", features = ["std"] }
[dev-dependencies]
criterion = "0.3"
rand = "0.8.4"
rand_chacha = "0.3.1"
rand_core = "0.6.3"
pretty_assertions = "1.3.0"