[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = { workspace = true }
serde = { worspace = true, features = ["rc"] }
anyhow = { workspace = true }
num-traits = { workspace = true }
prost = { workspace = true }
bytes = { workspace = true }
bincode = { workspace = true }
getset = { workspace = true }
# local deps
hex = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
directories = "4.0.1"

primitive-types = { path = "../primitive-types" }
smt = { path = "../../smt" }
codec = { path = "../../codec" }
crypto = { path = "../../crypto", features = ["std"] }
bech32 = { path = "../bech32", features = ["std"] }

[dev-dependencies]
criterion = "0.3"
rand = "0.8.4"
serde_json = "1.0"
rand_chacha = "0.3.1"
rand_core = "0.6.3"
pretty_assertions = "1.3.0"
[build-dependencies]
tonic-build = "0.8.0"