[package]
name = "prost-extra-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
doctest = false
test = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.36"
quote = "1.0.14"
syn = "1.0.84"

[dev-dependencies]
trybuild = "1.0.77"
prost = {workspace = true}
prost-extra = { path = "../prost-extra", features = ["derive"] }