name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.sanitizer == 'address' }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        sanitizer: [none]
        include:
          - os: ubuntu-latest
            sanitizer: address
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust (regular)
        if: matrix.sanitizer != 'address'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.58.1
          default: true
      - name: Setup Rust (for sanitizer)
        if: matrix.sanitizer == 'address'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-12-22
          default: true
      - name: APT dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt install clang libclang-dev llvm llvm-dev linux-kernel-headers libev-dev
          sudo apt install cmake libprotobuf-dev protobuf-compiler
      - name: OSX dependencies
        if: runner.os == 'macOS'
        run: |
          brew install --with-toolchain llvm
          brew install cmake automake libtool
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test