name: clippy

on:
  push:
    branches: [ master, develop ]
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-03
          components: rustfmt, clippy
          override: true
      - name: APT dependencies
        run: |
          sudo apt-get update -y
          sudo apt install clang libclang-dev llvm llvm-dev linux-kernel-headers libev-dev
          sudo apt install cmake libprotobuf-dev protobuf-compiler ninja-build
          rustup target add wasm32-unknown-unknown
      - name: lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets -- -A clippy::too_many_arguments -A clippy::doc_markdown